# Generated by Django 6.1 on 2026-08-29 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Project Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('category', models.CharField(choices=[('language', 'Language'), ('backend', 'Backend / Framework'), ('database', 'Database & Vector'), ('ai', 'AI / Machine Learning'), ('infrastructure', 'Infrastructure & DevOps'), ('security', 'Security & Networking'), ('other', 'Other Tools')], default='backend', max_length=50)),
                ('icon_name', models.CharField(blank=True, help_text='Icon identifier or CSS class', max_length=50)),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('tagline', models.CharField(help_text='Concise one-liner summary', max_length=250)),
                ('status', models.CharField(choices=[('concept', 'Concept'), ('prototype', 'Prototype'), ('active_dev', 'Active Development'), ('production', 'Production'), ('archived', 'Archived')], default='active_dev', max_length=30)),
                ('role', models.CharField(default='Lead Developer / System Architect', max_length=100)),
                ('featured', models.BooleanField(default=False, help_text='Highlight on homepage')),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('short_description', models.TextField(help_text='Card summary for list views')),
                ('overview', models.TextField(blank=True, help_text='Detailed executive overview')),
                ('problem_statement', models.TextField(blank=True, help_text='The real-world problem being solved')),
                ('solution_architecture', models.TextField(blank=True, help_text='System design and architecture breakdown')),
                ('implementation_details', models.TextField(blank=True, help_text='Key technical mechanisms, stack decisions')),
                ('challenges_and_solutions', models.TextField(blank=True, help_text='Engineering hurdles overcome')),
                ('security_and_governance', models.TextField(blank=True, help_text='Security, access controls, data safety')),
                ('results_and_impact', models.TextField(blank=True, help_text='Outcomes, metrics (factual only)')),
                ('lessons_learned', models.TextField(blank=True, help_text='Engineering takeaways')),
                ('future_roadmap', models.TextField(blank=True, help_text='Planned features and iterations')),
                ('repository_url', models.URLField(blank=True, help_text='GitHub repository URL')),
                ('live_url', models.URLField(blank=True, help_text='Live demonstration or deployment')),
                ('documentation_url', models.URLField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.category')),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='projects.technology')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-featured', 'order', '-created_at'],
            },
        ),
    ]
