services:
  web:
    image: ndoli/ndoli_dev:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ndoli_dev_web
    restart: always
    env_file:
      - .env
    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-ndoli.dev,www.ndoli.dev,62.171.182.99,localhost,127.0.0.1}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS:-https://ndoli.dev,https://www.ndoli.dev,http://62.171.182.99:8000,http://62.171.182.99}
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:Kigali@123@62.171.182.99:5437/ndoli?sslmode=disable}
      - EMAIL_HOST=${EMAIL_HOST:-smtp.gmail.com}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER:-ndolijeandamascene@gmail.com}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS:-True}
    ports:
      - "8000:8000"
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles

volumes:
  media_volume:
  static_volume:
