# Generated by Django 6.1 on 2026-08-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(default='NDOLI Jean Damascene', max_length=150)),
                ('short_brand', models.CharField(default='NDOLI', max_length=50)),
                ('role_title', models.CharField(default='IT Professional · Software Developer · Systems Builder', max_length=200)),
                ('hero_headline', models.CharField(default='I build practical digital systems, intelligent software, and technology solutions that solve real-world problems.', max_length=300)),
                ('snapshot_text', models.TextField(default='I am an IT professional and software developer focused on building practical digital systems. My work spans web applications, backend systems, databases, AI-assisted software, networking, cybersecurity, and technology solutions for real-world organizations.')),
                ('email', models.EmailField(default='contact@ndoli.dev', max_length=254)),
                ('location', models.CharField(default='Kigali, Rwanda', max_length=100)),
                ('github_url', models.URLField(blank=True, default='https://github.com/ndolijeandamascene')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com/in/ndoli-jean-damascene')),
                ('twitter_url', models.URLField(blank=True)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
