# Generated by Django 6.1 on 2026-08-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Organization or Company offering the role', max_length=150)),
                ('contact_person', models.CharField(help_text='Hiring Manager or Recruiter Name', max_length=120)),
                ('contact_email', models.EmailField(help_text='Official or Business Email', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Phone / WhatsApp number', max_length=50)),
                ('company_website', models.URLField(blank=True, help_text='Company website URL')),
                ('job_title', models.CharField(help_text='e.g., IT Officer, Systems Administrator, Django Developer', max_length=150)),
                ('job_category', models.CharField(choices=[('it_operations', 'IT Operations & Infrastructure'), ('systems_admin', 'Systems & Server Administration'), ('software_dev', 'Software & Web Development (Django/Python)'), ('helpdesk_support', 'ICT Help Desk & Technical Support'), ('ai_rag', 'AI, Vector Search & RAG Systems'), ('database_admin', 'Database Administration (PostgreSQL/MySQL)'), ('network_security', 'Networking & Cybersecurity'), ('it_management', 'IT Management & Leadership'), ('other', 'Other IT / Technology Role')], default='it_operations', max_length=50)),
                ('employment_type', models.CharField(choices=[('fulltime_onsite', 'Full-time (On-site)'), ('fulltime_hybrid', 'Full-time (Hybrid)'), ('fulltime_remote', 'Full-time (Remote)'), ('part_time', 'Part-time'), ('contract', 'Contract / Project-based'), ('consulting', 'IT Consulting / Advisory')], default='fulltime_onsite', max_length=40)),
                ('work_location', models.CharField(default='Kigali, Rwanda', help_text='Office city or Remote policy', max_length=150)),
                ('offered_salary', models.CharField(help_text='Proposed salary or budget (e.g., 1,500,000 RWF / month, $2,000 USD / month, or Negotiable)', max_length=120)),
                ('salary_currency', models.CharField(choices=[('RWF', 'RWF (Rwandan Franc)'), ('USD', 'USD ($)'), ('EUR', 'EUR (€)'), ('GBP', 'GBP (£)'), ('OTHER', 'Other')], default='RWF', max_length=10)),
                ('expected_start_date', models.CharField(blank=True, default='Immediate / Next 30 Days', max_length=100)),
                ('job_description', models.TextField(help_text='Summary of role responsibilities, project scope, or required qualifications')),
                ('status', models.CharField(choices=[('new', 'New Offer'), ('reviewed', 'Reviewed'), ('contacted', 'Contacted / In Discussion'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('archived', 'Archived')], default='new', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Job Offer / Hiring Request',
                'verbose_name_plural': 'Job Offers / Hiring Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='ndolijeandamascene@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='role_title',
            field=models.CharField(default='IT Operations Administrator · Systems Administrator · Software Developer', max_length=200),
        ),
    ]
