# Generated by Django 6.1 on 2026-08-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_joboffer_alter_sitesettings_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120)),
                ('role_title', models.CharField(max_length=150)),
                ('organization', models.CharField(max_length=150)),
                ('quote', models.TextField()),
                ('project_context', models.CharField(blank=True, help_text='e.g., Enterprise IT & Linux Infrastructure', max_length=150)),
                ('avatar_initials', models.CharField(blank=True, default='ND', max_length=5)),
                ('order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial / Endorsement',
                'verbose_name_plural': 'Testimonials / Endorsements',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='availability_badge',
            field=models.CharField(blank=True, default='Available for Full-time, Hybrid & Remote Roles', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='booking_url',
            field=models.URLField(blank=True, default='https://cal.com/ndolijeandamascene', help_text='Cal.com or Calendly direct booking link'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_number',
            field=models.CharField(blank=True, default='+250 789 317 65', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_url',
            field=models.URLField(blank=True, default='https://wa.me/25078931765'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='years_of_experience',
            field=models.CharField(blank=True, default='3+ Years', max_length=50),
        ),
    ]
