# Generated by Django 6.1 on 2026-09-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testimonial_sitesettings_availability_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_spam',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='spam_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='is_spam',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='spam_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='role_title',
            field=models.CharField(default='IT Professional · Software Developer · Systems Builder', max_length=200),
        ),
    ]
